// web/app/themes/sage/resources/react/Pages/Blog/BlogListing/Components/Posts/Posts.jsx
/**
 * React Scripts
 */
import {shallow} from "zustand/shallow";
import {setResultsCount} from "@reactUtil/mixins";
import blogStore from "@zustandBlog/store";

/**
 * React Components
 */
import Post from "@reactComponent/Post";
import Loading from "@reactComponent/Loading"
import NoResults from "@reactComponent/NoResults";

const Posts = () => {
    const {noResults} = BLOG;
    const {loading, posts, total} = blogStore(state => state, shallow)

    /**
     * Update the search count
     */
    setResultsCount('results-count', total)

    if (loading) {
        return <Loading fillColor="#ffffff"/>
    }

    if (posts.length) {
        return posts.map(post =>
            <Post key={post.id}
                  post={post}
                  firstItem={post.id === posts[0]?.id}
                  lastItem={post.id === posts.findLast(x => true)?.id}/>)
    }

    return <NoResults noResultsText={noResults} />
}

export default Posts;

// web/app/themes/sage/resources/vue/Blocks/PostsListing/Posts.vue
<template>
    <div class="blog-listing__results">
        <Post v-if="!loading && posts.length"
              v-for="({author, categories, date, excerpt, id, image, permalink, sticky, title}) in posts"
              :key="id"
              :author="author"
              :categories="categories"
              :date="date"
              :excerpt="excerpt"
              :first-item="id === posts[0]?.id"
              :image="image"
              :last-item="id === posts.findLast(x => true)?.id"
              :permalink="permalink"
              :sticky="sticky"
              :title="title"/>

        <NoResults v-if="!loading && !posts.length"
                   :noResultsText="noResults"/>

        <Loading v-if="loading"
                 white/>
    </div>
</template>

<script type="application/javascript">
    /**
     * Vue Scripts
     */
    import {store} from "../../Vuex/posts/store";

    /**
     * Vue Components
     */
    import Loading from "../../Components/Loading";
    import NoResults from "../../Components/NoResults";
    import Post from "./Components/Post";

    export default {
        props: {},
        data: () => ({
            resultsCountElm: document.getElementById('results-count')
        }),
        created() {
            store.dispatch('getPosts');
        },
        beforeMount() {
        },
        mounted() {
        },
        methods: {},
        components: {Loading, NoResults, Post},
        computed: {
            loading() {
                return store.state.loading
            },
            noResults() {
                return store.state.noResults
            },
            posts() {
                return store.state.posts
            },
            resultsLabel() {
                return store.state.resultsLabel
            },
            total() {
                return store.state.total
            },
        },
        watch: {
            total(newVal) {
                if (this.resultsCountElm) this.resultsCountElm.innerText = `: ${newVal}`;
            }
        },
        name: "PostListing"
    }
</script>

<style scoped lang="scss">

</style>
