// web/app/themes/sage/resources/vue/Components/NoResults.vue
<template>
  <div :class="containerClass">
    <div :class="paragraphClass"
         v-html="noResultsText" />
  </div>
</template>

<script type="application/javascript">
export default {
  props: {
    containerClass: String,
    noResultsText: String,
    paragraphClass: String,
  },
  name: "NoResults"
};
</script>

<style scoped>

</style>

// web/app/themes/sage/resources/react/Components/NoResults/NoResults.jsx
function NoResults(
    {noResultsText = '',
        containerClass = '',
        noResultSClass = '',

    }) {
    return (
        <div className={containerClass}>
            <div className={noResultSClass}
                 dangerouslySetInnerHTML={{__html: noResultsText}} />
        </div>
    )
}

export default NoResults;
